on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo contains is true
        if: contains('true', true)
      - run: echo invaid
        if: contains('true', this is invalid value)
