name: conditional test
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'true'
        id: 'out-true'
        run: echo "::set-output name=out::true"
      - name: validate true
        if: ${{ steps.out-true.outputs.out }}
        run: echo "validate true"

      - name: 'false'
        id: 'out-false'
        run: echo "::set-output name=out::false"
      - name: validate false
        if: ${{ steps.out-false.outputs.out }}
        run: echo "validate false"

      - name: '0'
        id: 'out-zero'
        run: echo "::set-output name=out::0"
      - name: validate zero
        if: ${{ steps.out-zero.outputs.out }}
        run: echo "validate zero"

      - name: '1'
        id: 'out-one'
        run: echo "::set-output name=out::1"
      - name: validate one
        if: ${{ steps.out-one.outputs.out }}
        run: echo "validate one"
